include:
  - Vendor/mc/mcxUIReusable/project.yml
  - Vendor/mc/mcxMediaExtensions/project.yml
  - Vendor/mc/mcxFoundationFormatters/project.yml
  - Vendor/mc/mcxMediaAU/project.yml
  - Vendor/mc/mcxUIPreviews/project.yml
name: Shared
settings:
  AWL_LIB_SRC: Vendor/mc
  MACOSX_DEPLOYMENT_TARGET: 10.12
aggregateTargets:
  Shared:
    targets:
      - mcxUIReusable
      - mcxMediaExtensions
      - mcxFoundationFormatters
      - mcxMediaAU
      - mcxUIPreviews
