include:
  - ../../../Projects/mc/templates.yml
  - ../../../Projects/mc/mcxUIReusable/project.yml
  - ../../../Projects/mc/mcxMediaExtensions/project.yml
  - ../../../Projects/mc/mcxFoundationFormatters/project.yml
  - ../../../Projects/mc/mcxMediaAU/project.yml
  - ../../../Projects/mc/mcxUIPreviews/project.yml
name: Shared
settings:
  AWL_LIB_SRC: Vendor/mc
  MACOSX_DEPLOYMENT_TARGET: 10.12
fileGroups:
   - project.yml
aggregateTargets:
  Shared:
    targets:
      - mcxUIReusable
      - mcxMediaExtensions
      - mcxFoundationFormatters
      - mcxMediaAU
      - mcxUIPreviews
